{
    "openapi": "3.0.0",
    "info": {
        "title": "API de torneios de Futebol",
        "description": "API para criação de torneios de futebol, partidas de futebol com seus respectivos eventos e times com seus jogadores.",
        "contact": {
            "name": "André Luis",
            "url": "https://github.com/acoutinho12",
            "email": "acoutinho12@outlook.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333/v1",
            "description": "API Local"
        }
    ],
    "paths": {
        "/times": {
            "post": {
                "summary": "Cadastro de time",
                "description": "Rota responsável pelo cadastro de um novo time",
                "tags": [
                    "Times"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TimeRequestBody"
                            }
                        }
                    }
                }
            }
        },
        "/times/{id}": {
            "get": {
                "summary": "Buscar time",
                "description": "Rota responsável pela busca de um time pelo id",
                "tags": [
                    "Times"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do time para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Time encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Time"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Time não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar time",
                "description": "Rota responsável por atualizar os dados de um time pelo id",
                "tags": [
                    "Times"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/Time"
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do time para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Time encontrado e atualizado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Time"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Time não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar time",
                "description": "Rota responsável por apagar um time pelo id",
                "tags": [
                    "Times"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do time para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Time encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Time"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Time não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/jogadores": {
            "post": {
                "summary": "Cadastro de jogador",
                "description": "Rota responsável pelo cadastro de um novo jogador",
                "tags": [
                    "Jogadores"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/JogadorRequestBody"
                            },
                            "examples": {
                                "jogador": {
                                    "value": {
                                        "nome": "André Luis",
                                        "dt_nascimento": "20/02/1993",
                                        "pais": "Brasil",
                                        "timeId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/jogadores/{id}": {
            "get": {
                "summary": "Buscar jogador",
                "description": "Rota responsável pela busca de um jogador pelo id",
                "tags": [
                    "Jogadores"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do jogador para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Jogador encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/Jogador"
                                },
                                "examples": {
                                    "jogador": {
                                        "value": {
                                            "id": 1,
                                            "nome": "André Luis",
                                            "dt_nascimento": "20/02/1993",
                                            "pais": "Brasil",
                                            "timeId": 1
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Jogador não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar jogador",
                "description": "Rota responsável por atualizar os dados de um jogador pelo id",
                "tags": [
                    "Jogadores"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/JogadorRequestBody"
                            },
                            "examples": {
                                "jogador": {
                                    "value": {
                                        "nome": "André Luis",
                                        "dt_nascimento": "20/02/1993",
                                        "pais": "Brasil",
                                        "timeId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do jogador para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Jogador encontrado e atualizado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Jogador"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Jogador não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar jogador",
                "description": "Rota responsável por apagar um jogador pelo id",
                "tags": [
                    "Jogadores"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do jogador para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Jogador encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Jogador"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Jogador não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/transferencias": {
            "post": {
                "summary": "Cadastro de transferencia",
                "description": "Rota responsável pelo cadastro de uma nova transferencia",
                "tags": [
                    "Transferencias"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TransferenciaRequestBody"
                            },
                            "examples": {
                                "transferencia": {
                                    "value": {
                                        "data": "20/02/1993",
                                        "valor": 300.00,
                                        "jogadorIdOrigem": 1,
                                        "timeIdOrigem": 1,
                                        "timeIdDestino": 2
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/transferencias/{id}": {
            "get": {
                "summary": "Buscar transferencia",
                "description": "Rota responsável pela busca de uma transferencia pelo id",
                "tags": [
                    "Transferencias"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do transferencia para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transferencia encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/Transferencia"
                                },
                                "examples": {
                                    "transferencia": {
                                        "value": {
                                            "id": 1,
                                            "data": "20/02/1993",
                                            "valor": 300.00,
                                            "jogadorIdOrigem": 1,
                                            "timeIdOrigem": 1,
                                            "timeIdDestino": 2
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Transferencia não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar transferencia",
                "description": "Rota responsável por atualizar os dados de um transferencia pelo id",
                "tags": [
                    "Transferencias"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TransferenciaRequestBody"
                            },
                            "examples": {
                                "transferencia": {
                                    "value": {
                                        "data": "20/02/1993",
                                        "valor": 300.00,
                                        "jogadorIdOrigem": 1,
                                        "timeIdOrigem": 1,
                                        "timeIdDestino": 2
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da transferencia para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transferencia encontrada e atualizada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Transferencia"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Transferencia não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar transferencia",
                "description": "Rota responsável por apagar um transferencia pelo id",
                "tags": [
                    "Transferencias"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da transferencia para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transferencia encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Transferencia"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Transferencia não encontrada pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/torneios": {
            "post": {
                "summary": "Cadastro de torneio",
                "description": "Rota responsável pelo cadastro de uma nova torneio",
                "tags": [
                    "Torneios"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TorneioRequestBody"
                            },
                            "examples": {
                                "torneio": {
                                    "value": {
                                        "nome": "Campeonato Mineiro",
                                        "dataInicio": "20/02/2022",
                                        "dataFim": "20/12/2022"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/torneios/{id}": {
            "get": {
                "summary": "Buscar torneio",
                "description": "Rota responsável pela busca de um torneio pelo id",
                "tags": [
                    "Torneios"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do torneio para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torneio encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/Torneio"
                                },
                                "examples": {
                                    "torneio": {
                                        "value": {
                                            "id": 1,
                                            "nome": "Campeonato Mineiro",
                                            "dataInicio": "20/02/2022",
                                            "dataFim": "20/12/2022"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Torneio não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar torneio",
                "description": "Rota responsável por atualizar os dados de um torneio pelo id",
                "tags": [
                    "Torneios"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TorneioRequestBody"
                            },
                            "examples": {
                                "torneio": {
                                    "value": {
                                        "nome": "Campeonato Mineiro",
                                        "dataInicio": "20/02/2022",
                                        "dataFim": "20/12/2022"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da torneio para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torneio encontrada e atualizada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Torneio"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Torneio não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar torneio",
                "description": "Rota responsável por apagar um torneio pelo id",
                "tags": [
                    "Torneios"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da torneio para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Torneio encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Torneio"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Torneio não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/partidas": {
            "post": {
                "summary": "Cadastro de partida",
                "description": "Rota responsável pelo cadastro de uma nova partida",
                "tags": [
                    "Partidas"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/PartidaRequestBody"
                            },
                            "examples": {
                                "partida": {
                                    "value": {
                                        "dataHoraInicio": "20/02/2022 15:00:00",
                                        "dataHoraFim": "20/02/2022 15:00:00",
                                        "dataHoraIntervalo": "20/02/2022 15:00:00",
                                        "estadio": "Mineirão",
                                        "timeCasaId": 1,
                                        "timeForaId": 2,
                                        "torneioId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/partidas/{id}": {
            "get": {
                "summary": "Buscar partida",
                "description": "Rota responsável pela busca de um partida pelo id",
                "tags": [
                    "Partidas"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do partida para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Partida encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/Partida"
                                },
                                "examples": {
                                    "partida": {
                                        "value": {
                                            "id": 1,
                                            "dataHoraInicio": "20/02/2022 15:00:00",
                                            "dataHoraFim": "20/02/2022 15:00:00",
                                            "dataHoraIntervalo": "20/02/2022 15:00:00",
                                            "estadio": "Mineirão",
                                            "timeCasaId": 1,
                                            "timeForaId": 2,
                                            "torneioId": 1
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Partida não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar partida",
                "description": "Rota responsável por atualizar os dados de um partida pelo id",
                "tags": [
                    "Partidas"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/PartidaRequestBody"
                            },
                            "examples": {
                                "partida": {
                                    "value": {
                                        "dataHoraInicio": "20/02/2022 15:00:00",
                                        "dataHoraFim": "20/02/2022 15:00:00",
                                        "dataHoraIntervalo": "20/02/2022 15:00:00",
                                        "estadio": "Mineirão",
                                        "timeCasaId": 1,
                                        "timeForaId": 2,
                                        "torneioId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da partida para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Partida encontrada e atualizada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Partida"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Partida não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar partida",
                "description": "Rota responsável por apagar um partida pelo id",
                "tags": [
                    "Partidas"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da partida para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Partida encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Partida"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Partida não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/tipo-eventos": {
            "post": {
                "summary": "Cadastro de tipoEvento",
                "description": "Rota responsável pelo cadastro de uma nova tipoEvento",
                "tags": [
                    "TipoEvento"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TipoEventoRequestBody"
                            },
                            "examples": {
                                "tipoEvento": {
                                    "value": {
                                        "nome": "Gol"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/tipo-eventos/{id}": {
            "get": {
                "summary": "Buscar tipoEvento",
                "description": "Rota responsável pela busca de um tipoEvento pelo id",
                "tags": [
                    "TipoEvento"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do tipoEvento para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "TipoEvento encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/TipoEvento"
                                },
                                "examples": {
                                    "tipoEvento": {
                                        "value": {
                                            "id": 1,
                                            "nome": "Gol"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "TipoEvento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar tipoEvento",
                "description": "Rota responsável por atualizar os dados de um tipoEvento pelo id",
                "tags": [
                    "TipoEvento"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/TipoEventoRequestBody"
                            },
                            "examples": {
                                "tipoEvento": {
                                    "value": {
                                        "nome": "Gol"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da tipoEvento para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "TipoEvento encontrada e atualizada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/TipoEvento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "TipoEvento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar tipoEvento",
                "description": "Rota responsável por apagar um tipoEvento pelo id",
                "tags": [
                    "TipoEvento"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do tipoEvento para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "TipoEvento encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/TipoEvento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "TipoEvento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/eventos": {
            "post": {
                "summary": "Cadastro de evento",
                "description": "Rota responsável pelo cadastro de uma nova evento",
                "tags": [
                    "Evento"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/EventoRequestBody"
                            },
                            "examples": {
                                "evento": {
                                    "value": {
                                        "tipoEventoId": 1,
                                        "jogadorId": 1,
                                        "timeId": 1,
                                        "partidaId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/eventos/{id}": {
            "get": {
                "summary": "Buscar evento",
                "description": "Rota responsável pela busca de um evento pelo id",
                "tags": [
                    "Evento"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do evento para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evento encontrado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#components/schemas/Evento"
                                },
                                "examples": {
                                    "evento": {
                                        "value": {
                                            "id": 1,
                                            "tipoEventoId": 1,
                                            "jogadorId": 1,
                                            "timeId": 1,
                                            "partidaId": 1
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "put": {
                "summary": "Atualizar evento",
                "description": "Rota responsável por atualizar os dados de um evento pelo id",
                "tags": [
                    "Evento"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/EventoRequestBody"
                            },
                            "examples": {
                                "evento": {
                                    "value": {
                                        "tipoEventoId": 1,
                                        "jogadorId": 1,
                                        "timeId": 1,
                                        "partidaId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id da evento para atualizar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evento encontrada e atualizada",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            },
            "delete": {
                "summary": "Apagar evento",
                "description": "Rota responsável por apagar um evento pelo id",
                "tags": [
                    "Evento"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do evento para apagar",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Evento encontrado e apagado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Evento não encontrado pelo id"
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/torneios/{idTorneio}/partidas/{idPartida}/eventos/gol": {
            "post": {
                "summary": "Cadastro de evento",
                "description": "Rota responsável pelo cadastro de um evento de gol",
                "tags": [
                    "Gol"
                ],
                "parameters": [
                    {
                        "name": "idTorneio",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    },
                    {
                        "name": "idPartida",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/EventoPartidaRequestBody"
                            },
                            "examples": {
                                "eventoPartida": {
                                    "value": {
                                        "jogadorId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Evento de gol criado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/torneios/{idTorneio}/partidas/{idPartida}/eventos/cartao-amarelo": {
            "post": {
                "summary": "Cadastro de evento",
                "description": "Rota responsável pelo cadastro de um evento de cartão amarelo",
                "tags": [
                    "Cartão Amarelo"
                ],
                "parameters": [
                    {
                        "name": "idTorneio",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    },
                    {
                        "name": "idPartida",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/EventoPartidaRequestBody"
                            },
                            "examples": {
                                "eventoPartida": {
                                    "value": {
                                        "jogadorId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Evento de cartão amarelo criado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        },
        "/torneios/{idTorneio}/partidas/{idPartida}/eventos/cartao-vermelho": {
            "post": {
                "summary": "Cadastro de evento",
                "description": "Rota responsável pelo cadastro de um evento de cartão vermelho",
                "tags": [
                    "Cartão Vermelho"
                ],
                "parameters": [
                    {
                        "name": "idTorneio",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    },
                    {
                        "name": "idPartida",
                        "in": "path",
                        "description": "id do torneio para criar o evento na partida",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#components/schemas/EventoPartidaRequestBody"
                            },
                            "examples": {
                                "eventoPartida": {
                                    "value": {
                                        "jogadorId": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Evento de cartão vermelho criado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#components/schemas/Evento"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor."
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "TimeRequestBody": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "localidade": {
                        "type": "string"
                    }
                }
            },
            "Time": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "localidade": {
                        "type": "string"
                    }
                }
            },
            "JogadorRequestBody": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "dt_nascimento": {
                        "type": "string",
                        "format": "date"
                    },
                    "pais": {
                        "type": "string"
                    },
                    "timeId": {
                        "type": "integer"
                    }
                }
            },
            "Jogador": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "dt_nascimento": {
                        "type": "string",
                        "format": "date"
                    },
                    "pais": {
                        "type": "string"
                    },
                    "timeId": {
                        "type": "integer"
                    }
                }
            },
            "Transferencia": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "data": {
                        "type": "string",
                        "format": "date"
                    },
                    "valor": {
                        "type": "number",
                        "format": "double"
                    },
                    "jogadorIdOrigem": {
                        "type": "integer"
                    },
                    "timeIdOrigem": {
                        "type": "integer"
                    },
                    "timeIdDestino": {
                        "type": "integer"
                    }
                }
            },
            "TransferenciaRequestBody": {
                "type": "object",
                "properties": {
                    "data": {
                        "type": "string",
                        "format": "date"
                    },
                    "valor": {
                        "type": "number",
                        "format": "double"
                    },
                    "jogadorIdOrigem": {
                        "type": "integer"
                    },
                    "timeIdOrigem": {
                        "type": "integer"
                    },
                    "timeIdDestino": {
                        "type": "integer"
                    }
                }
            },
            "Torneio": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "dataInicio": {
                        "type": "string",
                        "format": "date"
                    },
                    "dataFim": {
                        "type": "string",
                        "format": "date"
                    }
                }
            },
            "TorneioRequestBody": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "dataInicio": {
                        "type": "string",
                        "format": "date"
                    },
                    "dataFim": {
                        "type": "string",
                        "format": "date"
                    }
                }
            },
            "Partida": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "dataHoraInicio": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "dataHoraFim": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "dataHoraIntervalo": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "estadio": {
                        "type": "string"
                    },
                    "timeCasaId": {
                        "type": "integer"
                    },
                    "timeForaId": {
                        "type": "integer"
                    },
                    "torneioId": {
                        "type": "integer"
                    }
                }
            },
            "PartidaRequestBody": {
                "type": "object",
                "properties": {
                    "dataHoraInicio": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "dataHoraFim": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "dataHoraIntervalo": {
                        "type": "string",
                        "format": "datetime"
                    },
                    "estadio": {
                        "type": "string"
                    },
                    "timeCasaId": {
                        "type": "integer"
                    },
                    "timeForaId": {
                        "type": "integer"
                    },
                    "torneioId": {
                        "type": "integer"
                    }
                }
            },
            "TipoEventoRequestBody": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    }
                }
            },
            "TipoEvento": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "nome": {
                        "type": "string"
                    }
                }
            },
            "EventoRequestBody": {
                "type": "object",
                "properties": {
                    "tipoEventoId": {
                        "type": "integer"
                    },
                    "jogadorId": {
                        "type": "integer"
                    },
                    "timeId": {
                        "type": "integer"
                    },
                    "partidaId": {
                        "type": "integer"
                    }
                }
            },
            "Evento": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "tipoEventoId": {
                        "type": "integer"
                    },
                    "jogadorId": {
                        "type": "integer"
                    },
                    "timeId": {
                        "type": "integer"
                    },
                    "partidaId": {
                        "type": "integer"
                    }
                }
            },
            "EventoPartidaRequestBody": {
                "type": "object",
                "properties": {
                    "jogadorId": {
                        "type": "integer"
                    }
                }
            }
        }
    }
}